version: '3'
services:  
  db:
    image: mongo:4.2.8 
    container_name: db
    ports:
      - "4000:27017"
    restart: always
  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile-dev
    container_name: video-storage
    volumes:
      - /tmp/azure-storage/npm-cache:/root/.npm:z
      - ./azure-storage/src/:/usr/src/app/src:z
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - HOST=4001
      - STORAGE_ACCOUNT_NAME=anhtestvideos
      - STORAGE_ACCESS_KEY=
      - NODE-ENV=development
    restart: "no"
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src/:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - HOST=4002
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - NODE-ENV=development
    restart: "no"
  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src/:/usr/src/app/src:z
    ports:
      - 4003:80
    environment:
      - PORT=80
      - HOST=4003
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - NODE-ENV=development
    depends_on:
      - db
    restart: "no"